URLshortener/urls.py
from django.urls import path
from . import views

app_name = 'URLshortener'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about-us/', views.AboutUsView.as_view(), name='about-us'),
    path('shortened-url/<slug:slug>', views.URLRedirectView.as_view(), name='shortened-url'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('add-url/', views.AddURLView.as_view(), name='add-url'),
    path('edit-url/<slug:slug>', views.EditURLView.as_view(), name='edit-url'),
    path('delete-url/<slug:slug>', views.DeleteURLView.as_view(), name='delete-url'),
    path('profile-completion/', views.ProfileView.as_view(), name='profile-completion'),
    path('delete-photo/', views.DeletePhotoView.as_view(), name='delete-photo'),
    path('edit-profile/', views.EditProfileView.as_view(), name='edit-profile'),
    path('search-dropdown/', views.SearchDropdownView.as_view(), name='search-dropdown'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('URLshortener.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/register', 
        RegistrationView.as_view(success_url=reverse_lazy('URLshortener:profile-completion')),
        name='registration_register'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

URLshortener/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

from extensions.time_utils import datetime_to_jalali_str, date_to_jalali_str

# create your managers here


# Create your models here.

class URL(models.Model):
    label = models.CharField(blank=True, max_length=30, verbose_name='عنوان')
    address = models.URLField(max_length=512, verbose_name='نشانی اینترنتی')
    slug = models.SlugField(max_length=8, unique=True, verbose_name='اسلاگ')
    visits = models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید ها')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    last_visit = models.DateTimeField(default=timezone.now, verbose_name='آخرین بازدید')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='urls',
                               verbose_name='ایجاد کننده')

    def increase_visits(self):
        self.visits += 1
        self.last_visit = timezone.now()
        self.save()

    def last_visit_jalali(self):
        return datetime_to_jalali_str(self.last_visit)
    last_visit_jalali.short_description = 'آخرین بازدید'

    def created_jalali(self):
        return datetime_to_jalali_str(self.created)
    created_jalali.short_description = 'تاریخ ایجاد'

    def __str__(self):
        host = settings.ALLOWED_HOSTS[0] if settings.ALLOWED_HOSTS else 'localhost:8000'
        return '{}/shortened-url/{}'.format(host, self.slug)

    class Meta:
        verbose_name = 'نشانی اینترنتی'
        verbose_name_plural = 'نشانی های اینترنتی'


class UserProfile(models.Model):
    photo = models.ImageField(upload_to='profile_images', blank=True, verbose_name='تصویر')
    birth_date = models.DateField(null=True, blank=True, verbose_name='تاریخ تولد')
    website = models.URLField(null=True, blank=True, verbose_name='وب سایت')
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def birth_date_jalali(self):
        return date_to_jalali_str(self.birth_date) if self.birth_date else 'ثبت نشده'
    birth_date_jalali.short_description = 'تاریخ تولد'

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'پروفایل'
        verbose_name_plural = 'پروفایل ها'

URLshortener/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import URL, UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['photo', 'birth_date', 'website']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type':'date'}),
            'photo': forms.FileInput,
        }

URLshortener/views.py
from django.db.models import Q
from django.http.response import Http404
from django.views.generic.list import ListView
from django.views.generic.base import View, TemplateView, RedirectView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from django import forms
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse

from .models import URL, UserProfile
from .forms import UserForm, UserProfileForm
from extensions.slug_generation import generate_slug

import os

# helper functions

def search_urls(queryset, search_key):
    if not search_key:
        return queryset.order_by('-visits')
    return queryset.filter(
        Q(label__icontains=search_key) | Q(slug__icontains=search_key)
    ).order_by('-visits')

# Create your views here.

class HomeView(ListView):
    paginate_by = 10
    template_name = 'URLshortener/home.html'

    def get_queryset(self):
        key = self.request.GET.get('search_key')
        queryset = URL.objects.all()
        return search_urls(queryset, key)


class AboutUsView(TemplateView):
    template_name = 'URLshortener/about_us.html'


class URLRedirectView(RedirectView):
    permanant = True
    
    def get_redirect_url(self, slug):
        url = get_object_or_404(URL, slug=slug)
        url.increase_visits()
        return url.address


class DashboardView(LoginRequiredMixin, ListView):
    paginate_by = 10
    template_name = 'URLshortener/dashboard.html'

    def get_queryset(self):
        key = self.request.GET.get('search_key')
        queryset = self.request.user.urls
        return search_urls(queryset, key)


class SearchDropdownView(ListView):
    template_name = 'URLshortener/search_dropdown.html'

    def get_queryset(self):
        key = self.request.GET.get('search_key')
        search_page = self.request.GET.get('search_page')

        if search_page == 'home':
            queryset = URL.objects.all()
        elif search_page == 'dashboard':
            queryset = self.request.user.urls
        else:
            raise Http404()

        return search_urls(queryset, key)


class AddURLView(LoginRequiredMixin, CreateView):
    template_name = 'URLshortener/add_url.html'
    model = URL
    fields = ['label', 'address']

    def form_valid(self, form):
        url_obj = form.save(commit=False)
        url_obj.slug = generate_slug()
        url_obj.author = self.request.user
        url_obj.save()
        context = self.get_context_data()
        context['shortened_url'] = str(url_obj)
        return self.render_to_response(context)


class EditURLView(LoginRequiredMixin, UpdateView):
    template_name = 'URLshortener/edit_url.html'
    model = URL
    fields = ['label']

    def get_object(self):
        return get_object_or_404(URL, slug=self.kwargs['slug'], author=self.request.user)

    def get_success_url(self):
        return self.request.GET.get('next', reverse('URLshortener:home'))


class DeleteURLView(LoginRequiredMixin, View):
    def get(self, request, slug):
        url_obj = get_object_or_404(URL, slug=slug, author=request.user)
        url_obj.delete()
        redirect_url = self.get_redirect_url()
        return redirect(redirect_url)

    def get_redirect_url(self):
        next_url = self.request.GET.get('next')
        page_num = int(self.request.GET.get('page', 1))
        rem_urls = int(self.request.GET.get('rem_urls', 1))

        if rem_urls == 1 and page_num > 1:
            return '{}?page={}'.format(next_url, page_num - 1)
        else:
            return '{}?page={}'.format(next_url, page_num)


class ProfileView(LoginRequiredMixin, CreateView):
    model = UserProfile
    fields = ['photo', 'birth_date', 'website']
    template_name = 'URLshortener/profile_completion.html'
    success_url = reverse_lazy('URLshortener:dashboard')

    def get_form(self):
        form = super().get_form()
        form.fields['birth_date'].widget = forms.DateInput(attrs={'type':'date'})
        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.photo = self.request.FILES.get('photo')
        return super().form_valid(form)


class DeletePhotoView(LoginRequiredMixin, View):
    def get(self, request):
        photo_path = request.user.profile.photo.path
        if os.path.exists(photo_path):
            os.remove(photo_path)
        request.user.profile.photo = None
        request.user.profile.save()
        return redirect('URLshortener:dashboard')


class EditProfileView(LoginRequiredMixin, View):
    template_name = 'URLshortener/edit_profile.html'

    def get_context_data(self):
        context = {
            'user_form': UserForm(self.request.POST or None, instance=self.request.user),
            'profile_form': UserProfileForm(self.request.POST or None, 
                self.request.FILES or None, instance=self.request.user.profile),
        }
        return context

    def get(self, request):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request):
        context = self.get_context_data()

        if context['user_form'].is_valid() and context['profile_form'].is_valid():
            context['user_form'].save()
            context['profile_form'].save()
            return redirect('URLshortener:dashboard')
        else:
            return render(request, self.template_name, context)

templates/URLshortener/about_us.html
{% extends 'URLshortener/base.html' %}
{% load custom_tags %}
{% load static %}

{% block head %}
    <link rel='stylesheet' href="{% static 'URLshortener/css/about_us.css' %}">
    <title>About Us</title>
{% endblock %}

{% block main %}
    <div class='container-fluid p-3 m-0'>
        <div class='container border p-3 rounded about-us'>
            <div class='text-justify text-white p-2'>{% about_us_text %}</div>
            <div class='text-right text-white p-1'>
                <span>رفتن به: </span>
                <br>
                <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:home' %}">صفحه اصلی</a>
                <br>
                {% if user.is_authenticated %}
                <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:dashboard' %}">پنل کاربری</a>
                <br>
                <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:add-url' %}">کوتاه کردن نشانی</a>
                {% else %}
                <a class='btn btn-light py-1 m-1' href="{% url 'registration_register' %}">صفحه ثبت نام</a>
                <br>
                <a class='btn btn-light py-1 m-1' href="{% url 'auth_login' %}">ورود</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/URLshortener/add_url.html
{% extends 'URLshortener/base_form.html' %}
{% load static %}

{% block head %} <title>Add URL</title> {% endblock %}

{% block form_title %}اضافه کردن URL {% endblock %}

{% block form_id %}add-url{% endblock %}

{% block form_action %}{% url 'URLshortener:add-url' %}{% endblock %}

{% block submit_btn %}
    {% if not shortened_url %}
        <button id='submit' type='submit' class='btn btn-primary py-1 px-2'>کوتاه کردن</button>
    {% endif %}
{% endblock %}


{% block additional_content %}
    {% if shortened_url %}
        <div class='p-1 text-center'>
            <div class='text-right text-white p-1'>آدرس کوتاه شده:</div>
            <input class='text-left d-block' id='shortened-url' type="url" maxlength="512"
                value='{{ shortened_url }}' readonly>
            <button id='copy-btn' class='btn btn-primary m-2'>کپی کردن آدرس</button>
        </div>

        <div class='text-right text-white'>
            <span>رفتن به: </span>
            <br>
            <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:home' %}">صفحه اصلی</a>
            <br>
            <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:dashboard' %}">پنل کاربری</a>
            <br>
            <a class='btn btn-light py-1 m-1' href="{% url 'URLshortener:add-url' %}">کوتاه کردن نشانی دیگر</a>
        </div>
    {% endif %}
{% endblock %}

{% block js_links %}
    <script src='{% static "URLshortener/js/add_url.js" %}'></script>
{% endblock %}

templates/URLshortener/dashboard.html
{% extends 'URLshortener/base.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}

{% block head %}
	<link rel='stylesheet' href="{% static 'URLshortener/css/dashboard.css' %}">
	<title> Dashboard </title>
{% endblock %}

{% block header %}
    <div class='container-fluid row p-0 m-0'>
        <div class='col-sm-3 p-2 text-center'>
            {% if user.profile.photo %}
            <img class='w-100 rounded-circle img-thumbnail' src='{{ user.profile.photo.url }}'>
            <button id='delete-photo' class='btn btn-success m-1'>حذف تصویر</button>
            {% else %}
            <img class='w-100 rounded-circle img-thumbnail' src='{% static "URLshortener/images/user_avatar.png" %}'>
            {% endif %}
        </div>
        <div class='col-sm-9 text-white text-right p-2'>
            <div class='user-info p-2'>
                <div class='row p-2'>
                    <div class='col-sm-5'>نام کاربری:</div>
                    <div class='col-sm-7'>{{ user.username }}</div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>نام:</div>
                    <div class='col-sm-7'>
                        {% if user.first_name %}
                            {{ user.first_name }}
                        {% else %}
                            ثبت نشده
                        {% endif %}
                    </div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>نام خانوادگی:</div>
                    <div class='col-sm-7'>
                        {% if user.last_name %}
                            {{ user.last_name }}
                        {% else %}
                            ثبت نشده
                        {% endif %}
                    </div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>تاریخ تولد:</div>
                    <div class='col-sm-7'>{{ user.profile.birth_date_jalali }}</div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>ایمیل:</div>
                    <div class='col-sm-7'>{{ user.email }}</div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>وب سایت:</div>
                    <div class='col-sm-7'>
                        {% if user.profile.website %}
                            {{ user.profile.website }}
                        {% else %}
                            ثبت نشده
                        {% endif %}
                    </div>
                </div>
                <div class='row p-2'>
                    <div class='col-sm-5'>تعداد نشانی های کوتاه شده:</div>
                    <div class='col-sm-7'>{{ page_obj.paginator.count|to_persian }}</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block main %}
    <div class='row container-fluid p-0 m-0'>
        <aside class='col-sm-3 p-2 m-0'>
            <ul class='nav flex-column text-center text-white p-0 m-0 rounded border'>
                <li class="nav-item p-2">
                    <a class='d-block' href="{% url 'URLshortener:dashboard' %}">
                        <i style="font-size:24px"  class="fa">&#xf0e4;</i>
                    </a>
                </li>
                <li class="nav-item p-2"><a class='d-block' href="{% url 'URLshortener:home' %}" >صفحه اصلی</a></li>
                <li class="nav-item p-2"><a class='d-block' href="{% url 'URLshortener:add-url' %}" >اضافه کردن نشانی</a></li>
                <li class="nav-item p-2"><a class='d-block' href="{% url 'URLshortener:edit-profile' %}" >ویرایش اطلاعات</a></li>
                <li class="nav-item p-2"><a class='d-block' href="{% url 'auth_logout' %}?next=/" >خروج</a></li>
            </ul>
        </aside>
        <div class='col-sm-9 p-2 m-0'>
            <div class='container text-center text-white p-2 main-title'>
                نشانی های اضافه شده
                {% search_field 'dashboard' %}
            </div>
            {% if page_obj %}
                <div class='container p-0 my-2 mx-auto'>
                    {% url_cards page_obj %}
                </div>
            {% else %}
                <div class='alert alert-info text-right p-2 m-2 mx-auto'>
                    هنوز هیچ نشانی ای توسط شما اضافه نشده است!
                </div>
            {% endif %}

            {% if is_paginated %}
                {% paginator page_obj %}
            {% endif %}
        </div>
    </div>

    <div id="delete-photo-overlay" class="text-right d-none overlay">
        <span id='close-delete-photo' class="p-0 m-0 close-btn">&#x2715;</span>
        <div class="card p-3 text-center mx-auto overlay-content">
            <div>تصویر پروفایل حذف شود؟</div>
            <div class='text-center m-2'>
                <a href="{% url 'URLshortener:delete-photo' %}" class='btn btn-success py-1'>بله</a>
                <button id='cancel-delete-photo' class='btn btn-danger py-1'>خیر</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_links %}
    <script src="{% static 'URLshortener/js/dashboard.js' %}"></script>
    <script src="{% static 'URLshortener/js/url_cards.js' %}"></script>
    <script src="{% static 'URLshortener/js/search_field.js' %}"></script>
{% endblock %}

templates/URLshortener/edit_profile.html
{% extends 'URLshortener/base_form.html' %}

{% block head %} <title>User Profile</title> {% endblock %}

{% block form_title %} ویرایش اطلاعات {% endblock %}

{% block form_body %}
    <form id='edit-profile' class='mx-auto p-2' method='post'
        action="{% url 'URLshortener:edit-profile' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {% for error in user_form.non_field_errors %}
            <div class='alert alert-danger alert-dismissable text-right small p-2 my-1 mx-auto'>	
                <button type="button" class="close float-left" data-dismiss="alert">&times; </button>
                {{ error }}
            </div>
        {% endfor %}

        {% for error in profile_form.non_field_errors %}
            <div class='alert alert-danger alert-dismissable text-right small p-2 my-1 mx-auto'>	
                <button type="button" class="close float-left" data-dismiss="alert">&times; </button>
                {{ error }}
            </div>
        {% endfor %}

        {% for field in user_form.visible_fields %}
            <div class='row p-1'>
                <div class='col-sm-5 text-right px-2'>{{ field.label_tag }}</div>
                <div class='col-sm-7 text-center px-2'>{{ field }}</div>
            </div>
            
            {% for error in field.errors %}
                <div class='alert alert-danger alert-dismissable text-right small p-2 my-1 mx-auto'>
                    <button type="button" class="close float-left" data-dismiss="alert">&times; </button>
                    {{ error }}
                </div>
            {% endfor %}
        {% endfor %}

        {% for field in profile_form.visible_fields %}
            <div class='row p-1'>
                <div class='col-sm-5 text-right px-2'>{{ field.label_tag }}</div>
                <div class='col-sm-7 text-center px-2'>{{ field }}</div>
            </div>
            
            {% for error in field.errors %}
                <div class='alert alert-danger alert-dismissable text-right small p-2 my-1 mx-auto'>
                    <button type="button" class="close float-left" data-dismiss="alert">&times; </button>
                    {{ error }}
                </div>
            {% endfor %}
        {% endfor %}

        <div class='text-center p-2'>
            <button id='submit' type='submit' class='btn btn-primary py-1 px-2'>ذخیره</button>
        </div>
    </form>
{% endblock %}

templates/URLshortener/edit_url.html
{% extends 'URLshortener/base_form.html' %}
{% load static %}

{% block head %} <title>Edit URL</title> {% endblock %}

{% block form_title %} ویرایش URL {% endblock %}

{% block form_id %}edit-url{% endblock %}

{% block form_action %}{% url 'URLshortener:edit-url' form.instance.slug %}?next={{request.GET.next}}{% endblock %}

{% block submit_value %} ذخیره {% endblock %}

{% block info %}
    <div class='row p-1'>
        <div class='col-sm-5 text-right text-white px-2'>آخرین بازدید:</div>
        <div class='col-sm-7 text-center px-2'>
            <span class='badge badge-info p-2'>{{ form.instance.last_visit_jalali }}</span>
        </div>
    </div>

    <div class='text-center card p-1 my-2'>
        <a class='btn btn-link btn-block p-0 m-0' href="{% url 'URLshortener:shortened-url' form.instance.slug %}">
            {{ form.instance }}
        </a>
    </div>
{% endblock %}

templates/URLshortener/home.html
{% extends 'URLshortener/base.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}

{% block head %}
	<link rel='stylesheet' href="{% static 'URLshortener/css/home.css' %}">
	<title> Home </title>
{% endblock %}

{% block header %}
	<nav class='navbar navbar-expand-sm navbar-dark p-0'>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			<span class="navbar-toggler-icon text-white"></span>
		</button>

		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<ul class="navbar-nav text-center p-0 m-0">
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'URLshortener:home' %}">
						<i style="font-size:24px" class="fa">&#xf015;</i>
					</a>
				</li>
			{% if user.is_authenticated %}
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'URLshortener:dashboard' %}">پنل کاربری</a>
				</li>
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'URLshortener:add-url' %}">کوتاه کردن نشانی</a>
				</li>
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'auth_logout' %}?next=/">خروج</a>
				</li>
			{% else %}
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'registration_register' %}">ثبت نام</a>
				</li>
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'auth_login' %}">ورود</a>
				</li>
			{% endif %}
				<li class="nav-item p-1 text-center">
					<a class="nav-link" href="{% url 'URLshortener:about-us' %}">درباره ما</a>
				</li>
			</ul>
		</div>
	</nav>
	<div class='row container-fluid text-right p-5 text-white header-title'>
		کوتاه نشانی اینترنتی گستر ایران زمین
	</div>
{% endblock %}

{% block main %}
	<div class='container-fluid p-2'>
		<div class='container-fluid text-center text-white p-2 main-title'>
			پر بازدید ترین نشانی های کوتاه شده
			{% search_field 'home' %}
		</div>
		<div class='container'>
			{% if page_obj %}
				{% url_cards page_obj %}
			{% else %}
				<div class='alert alert-info text-right p-2 m-2 mx-auto'>
					هنوز هیچ نشانی ای اضافه نشده است!
				</div>
			{% endif %}

			{% if is_paginated %}
				{% paginator page_obj %}
			{% endif %}
		</div>
	</div>
{% endblock %}

{% block js_links %}
	<script src="{% static 'URLshortener/js/url_cards.js' %}"></script>
	<script src="{% static 'URLshortener/js/search_field.js' %}"></script>
{% endblock %}

templates/URLshortener/search_dropdown.html
{% load custom_filters %}
<div class='dropdown-content p-0 m-0 w-100'>
{% for url in url_list|slice:":5" %}
    <div class='card m-0 p-0 search-item'>
        <div class='row m-0 p-0'>
            <div class='col-md-3 m-0 p-1 text-center'>
                <span class='badge badge-success p-2'>{{ url.label }}</span>
                <span class='badge badge-info p-2'>{{ url.visits|to_persian }} بازدید</span>
            </div>
            <div class='col-md-9 m-0 p-1 text-center'>
                <a class='btn btn-link btn-block p-0 m-0' href="{% url 'URLshortener:shortened-url' url.slug %}">
                    {{ url }}
                </a>
            </div>
        </div>
    </div>
{% endfor %}
    <div class='bg-light text-dark text-right p-1'>
        <span class='p-1'>...</span>
        <br>
        <span class='p-1'>{{ url_list.count|to_persian }} مورد یافت شد</span>
    </div>
</div>

templates/URLshortener/search_field.html
<div class='container-fluid text-center mx-auto my-0 p-2 search-box'>
    <form class='row w-100 p-0 m-0' method='get' action='{{ request.path }}'>
        <input id='search-field' name='search_key' type='text'
            placeholder='عنوان یا کد یکتای ۸ رقمی را جست و جو کنید'
            class='d-block col-10 p-1 m-0 rounded' url='{% url "URLshortener:search-dropdown" %}'
            search_page='{{ search_page }}' required>
        
        <button id='search-btn' class='btn btn-block col-2 p-1 m-0 rounded bg-primary text-white search-btn' href=''>
            <i style="font-size:20px"  class="fa">&#xf002;</i>
        </button>
    </form>
    <div id='search-result' class='w-100 text-center p-0 m-0 search-result'></div>
    {% if request.GET.search_key %}
        <div class='text-right p-2 search-info'>
            نتایج جست و جو برای "{{ request.GET.search_key }}"
        </div>
    {% endif %}
</div>

templates/URLshortener/url_cards.html
{% load custom_filters %}

<div class='container-fluid m-0 p-2 d-flex flex-row flex-wrap justify-content-center cards-div'>
    {% for short_url in page %}
    <div class='card text-right m-1 p-1 url-card'>
        <h4 class='text-center p-0 m-0 url-number'>
            <span class='badge badge-pill badge-primary'>
                {{ forloop.counter0|add:page.start_index|to_persian }}
            </span>
        </h4>
        <hr class='mt-1 mb-0'>

        <div class='p-1'>
            <span class='badge badge-info p-2'>{{ short_url.visits|to_persian }} بازدید</span>
            <span></span>
            <span class='badge badge-success p-2'>{{ short_url.label }}</span>
        </div>
        <div class='row p-1 m-0'>
            <div class='col-sm-4 m-0 p-0'>آخرین بازدید:</div>
            <div class='col-sm-8 m-0 p-0 text-center'>
                <span class='badge badge-secondary p-2'>{{ short_url.last_visit_jalali }}</span>
            </div>
        </div>

        <div class='row p-1 m-0'>
            <div class='col-sm-3 m-0 p-0'>آدرس:</div>
            <div class='col-sm-9 m-0 p-0 text-center'>
                <a class='btn btn-link btn-block p-1 m-0' href="{% url 'URLshortener:shortened-url' short_url.slug %}">
                    {{ short_url }}
                </a>
            </div>
        </div>

        {% if short_url.author == request.user %}
            <hr class='mt-0 mb-1'>
            <div class='container-fluid text-center url-delete'>
                <a class='btn btn-dark py-0' href='{% url "URLshortener:edit-url" short_url.slug %}?next={{request.get_full_path}}'>ویرایش</a>
                <a label='{{ short_url.label }}' address='{{ short_url }}'
                    request_url="{% url 'URLshortener:delete-url' short_url.slug %}?next={{request.path}}&page={{page.number}}&rem_urls={{page|length}}"
                    class='btn btn-danger py-0 delete-url'>حذف</a>
            </div>
        {% endif %}

    </div>
    {% endfor %}
</div>

<div id="delete-url-overlay" class="text-right d-none overlay">
    <span id='close-delete-url' class="p-0 m-0 close-btn">&#x2715;</span>
    <div class="card p-3 text-center mx-auto overlay-content">
        <div id='delete-url-message'></div>
        <div class='text-center m-2'>
            <a id='delete-url-confirm' class='btn btn-success py-1'>بله</a>
            <button id='cancel-delete-url' class='btn btn-danger py-1'>خیر</button>
        </div>
    </div>
</div>